# https://taskfile.dev
version: "3"
dotenv: ['.env']
vars:
  CODE_DIRS: src/ tests/
  PYTHON: python3
  SET_VENV: uv run
  DOCKER_BUILDKIT: 1
  DOCKER_BUILD_ARGS: >-
    --build-arg HTTP_PROXY --build-arg HTTPS_PROXY --build-arg NO_PROXY
    --build-arg CI_REGISTRY
    --build-arg PYTHON_VERSION
    --build-arg BASE_IMAGE_NAME --build-arg BASE_IMAGE_TAG
  DOCKER_RUN_ARGS: >-
    -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY
    -v $(pwd)/:/build/ -w /build/


includes:
  b2v:
    taskfile: ./taskfiles/b2v.yml
  docs:
    taskfile: ./taskfiles/mkdocs.yml
  uv:
    taskfile: ./taskfiles/uv.yml
  ruff:
    taskfile: ./taskfiles/ruff.yml
  pytest:
    taskfile: ./taskfiles/pytest.yml
  mypy:
    taskfile: ./taskfiles/mypy.yml
  pre-commit:
    taskfile: ./taskfiles/pre-commit.yml
  nox:
    taskfile: ./taskfiles/nox.yml

tasks:
  env:
    desc: Print environment variables
    cmds:
      - |
        set -a; source .env; set +a;
        env | grep -E '(HOME|PATH|IMAGE|DOCKER|TAG|PYTHON|REGISTRY|URL|CI_)'

  env-info:
    desc: Print environment info
    cmds:
      - task: uv:env-info
    silent: true

  export:
    desc: Export dependencies
    cmds:
      - echo "Exporting dependencies to requirements.txt"
      - uv export -o requirements.txt --no-install-project --no-default-groups --no-hashes --no-header --no-editable --quiet

  install:
    desc: Install current project and required dependencies
    cmds:
      - echo "Installing current project and required dependencies"
      - uv sync --no-editable --active --all-extras

  install-inexact:
    desc: Install current project and required dependencies, also do not remove extraneous packages present in the environment
    cmds:
      - echo "Installing current project and required dependencies"
      - uv sync --no-editable --active --all-extras --inexact

  install-only-main:
    desc: Install only main required dependencies
    cmds:
      - echo "Installing only main dependencies"
      - uv sync --no-default-groups --no-dev --active --all-extras

  install-with-test:
    desc: Install required dependencies with test dependencies
    cmds:
      - echo "Install required dependencies with test dependencies"
      - uv sync --group test --active --all-extras --inexact

  install-all:
    desc: Install all dependencies including the current project
    cmds:
      - echo "Installing all dependencies including the current project"
      - uv sync --all-groups --active --all-extras

  install-only-deps:
    desc: Install only the dependencies and not including the current project
    cmds:
      - uv sync --no-install-project --all-groups

  install-with-devtest:
    desc: Install required dependencies
    cmds:
      - echo "Install required dependencies with test dependencies"
      - uv sync --group test --group dev --active --all-extras --inexact

  clean:
    desc: Clean up the installed dependencies
    cmds:
      - rm -rf .venv

  reinstall:
    desc: Clean up and reinstall required dependencies
    cmds:
      - task: clean
      - task: install

  update:
    desc: Update dependencies
    cmds:
      - echo "Updating dependencies"
      - uv sync --no-install-project --all-groups --upgrade

  init-git:
    desc: Initialize git repository
    cmds:
      - git init
      - git add LICENSE
      - "git commit -m 'chore: Initial commit'"
      - git branch -M main

  init:
    desc: Initialize project
    cmds:
      - task: init-git
      - task: install
      - task: pre-commit:install

  activate-venv:
    desc: Activate virtual environment
    cmds:
      - echo "To activate the virtual environment, run 'source .venv/bin/activate' in your shell."

  build:
    desc: Build package
    cmds:
      -  uv build --sdist --wheel --verbose

  run:
    desc: Run the main application
    deps: [install-inexact]
    cmds:
      - uv run gitlab-ci

  static-analysis:
    desc: Run code formatter check, linting, static type analysis
    cmds:
      - echo "Running static analysis"
      - task: install-with-devtest
      - task: install-inexact
      - task: ruff:check
      - task: ruff:format
      - task: mypy:check

  test-shell:
    desc: Run shell scripts tests
    cmds:
      - uv run scripts/test.sh

  test-suite:
    desc: Run all tests
    cmds:
      - task: static-analysis
      - task: pytest:all-nocov

  test-vault:
    desc: Run vault tests
    cmds:
      - tests/vault/test_generate_envconsul_config.sh
      - python -m pytest -m vault -x -l -vv -s --import-mode prepend

  test-suite-py3.*:
    desc: Run all tests with Python 3.*
    cmds:
      - task: ruff:check
        vars:
          SET_VENV: uv run --isolated --python 3.{{index .MATCH 0}}
      - task: ruff:format
        vars:
          SET_VENV: uv run --isolated --python 3.{{index .MATCH 0}}
      - task: black:format
        vars:
          SET_VENV: uv run --isolated --python 3.{{index .MATCH 0}}
      - task: mypy:check
        vars:
          SET_VENV: uv run --isolated --python 3.{{index .MATCH 0}}
      - task: pytest:all-cov
        vars:
          SET_VENV: uv sync --python 3.{{index .MATCH 0}} --group test && uv run --python 3.{{index .MATCH 0}}

  shell-check:
    desc: Run static analysis tool (linter) for shell scripts
    cmds:
      - >-
          docker run --rm -it {{.DOCKER_RUN_ARGS}}
          koalaman/shellcheck-alpine:latest
          sh -c "shellcheck --version && echo 'Checking...' && find scripts -name '*.sh' -exec shellcheck {} + && echo 'Done'"

  dockerfile-check:
    desc: Run static analysis tool (linter) for Dockerfile
    cmds:
      - >-
          docker run --rm -it {{.DOCKER_RUN_ARGS}}
          hadolint/hadolint:latest-alpine
          sh -c 'hadolint --version && echo "Checking..." && hadolint --failure-threshold warning Dockerfile && echo "Done"'

  build-image:
    desc: Build docker image
    cmds:
      - task: install
      - rm -rf dist/
      - |
        echo "Build from base image ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}"
        export DOCKER_BUILDKIT={{.DOCKER_BUILDKIT}}
        docker buildx build {{.DOCKER_BUILD_ARGS}} \
        --progress plain \
        -t local/${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG} .

  rebuild-image:
    desc: ReBuild docker image
    cmds:
      - task: build-image
        vars:
          DOCKER_BUILD_ARGS: '{{.DOCKER_BUILD_ARGS}} --no-cache'

  test-image:
    desc: Test docker image
    cmds:
      - |
        docker run --rm -it {{.DOCKER_RUN_ARGS}} \
        --entrypoint "./scripts/test-image.sh" \
        local/${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}

  build-and-test:
    desc: Build and test docker image
    cmds:
      - task: build-image
      - task: test-image

  run-image:
    desc: Run docker image
    cmds:
      - task: build-image
      - |
        docker run --rm -it {{.DOCKER_RUN_ARGS}} \
        local/${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG} sh

  changelog:
    desc: Generate changelog
    cmds:
      - >-
        docker run --rm -it {{.DOCKER_RUN_ARGS}}
        --entrypoint ""
        ghcr.io/orhun/git-cliff/git-cliff:latest
        sh -c "git-cliff --version && git-cliff -r . -o /tmp/CHANGELOG.md && echo 'Changelog generated' && cat /tmp/CHANGELOG.md"

  create-gh-release:
    desc: Create GitHub release
    cmds:
      - gh release create $(uvx bump-my-version show current_version) --generate-notes
