# These variables are used to build image and can be overridden in the CI/CD settings.
variables:
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
  PYTHON_VERSION:
    description: "Python version to use for the ghcr.io/astral-sh/uv:python docker image (e.g., 3.10)"
    value: "3.12"
  REGISTRY_URL:
    description: "Docker registry URL to use for the build (e.g., ghcr.io/alexchay)"
    value: ghcr.io/alexchay
  BASE_IMAGE_NAME: $REGISTRY_URL/python-base
  BASE_IMAGE_TAG:
    description: "Base image tag to use for the build (e.g., 3.12.2-slim)"
    value: "3.12"
  BUILD_IMAGE_NAME: gitlab-ci
  BUILD_IMAGE_TAG:
    description: "Image tag to use for the build (e.g., 3.12.2-slim)"
    value: "0.2.0"
  BUILD_IMAGE_TAGS:
    description: "Comma-separated list of tags to apply to the image (e.g., 3.12.2-slim, latest)"
    value: "latest"
  PLATFORMS: linux/amd64,linux/arm64
